#!/bin/bash -l

# Usage:
# 1. Copy to the directory where you have your files
# 2. Update any needed environment variables and input file names in this script
# 3. qsub job_improv

#PBS -A Radiant
#PBS -l select=30:ncpus=128:mpiprocs=8:ompthreads=16
#PBS -l walltime=03:00:00
#PBS -q compute
#PBS -j oe
#PBS -N cardinal

#PBS -m bea

nodes=30
num_numa=8
cores_per_numa=8
let threads_per_numa=$cores_per_numa*2
let ntasks=$num_numa*$nodes

module purge
module load gcc/11.4.0
module load openmpi/4.1.6-gcc-11.4.0-pbs
module load cmake/3.27.4
module load perl/5.38.0-gcc-11.4.0
module load miniforge3/25.3.0

# Moving into the working directory (where the job script was launched).
cd $PBS_O_WORKDIR

# Run a Cardinal case
rm logfile
rm statepoint*
mpirun -np $ntasks --bind-to numa --map-by numa openmc -s $threads_per_numa model.xml > logfile
